imgmath and mathjax conflict, keep mathjax, in doc gen
Attempt to fix this error:

```
Running Sphinx v1.5.3
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/scidb-py/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/scidb-py/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 199, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/scidb-py/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 523, in setup_extension
    ext_meta = mod.setup(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/scidb-py/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/mathjax.py", line 72, in setup
    raise ExtensionError('sphinx.ext.mathjax: other math package is already loaded')
ExtensionError: sphinx.ext.mathjax: other math package is already loaded

Extension error:
sphinx.ext.mathjax: other math package is already loaded
```