Replace pngmath with imgmath due to deprecation, in docs gen
Generating the docs on readthedocs.org generates the following error:

Running Sphinx v1.5.3
making output directory...
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/scidb-py/envs/latest/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/scidb-py/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 199, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/scidb-py/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 523, in setup_extension
    ext_meta = mod.setup(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/scidb-py/envs/latest/lib/python2.7/site-packages/sphinx/ext/mathjax.py", line 72, in setup
    raise ExtensionError('sphinx.ext.mathjax: other math package is already loaded')
ExtensionError: sphinx.ext.mathjax: other math package is already loaded

Extension error:
sphinx.ext.mathjax: other math package is already loaded